import { Side } from "@/components/admin";
import Header from "@/components/admin/header";
import { loginIsRequiredServer } from "@/lib/auth";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await loginIsRequiredServer();
  return (
    <html lang="en">
      <body className="w-full">
        <div className="flex w-full bg-[#1D1E24]">
          <div className="">
            <Side />
          </div>
          <div className="border-none w-full">
            <div className="w-full border py-1 border-custom-font">
              <Header />
            </div>
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
